name: Hawaii Counter Updater

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  counterRunner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Determine day difference
        run: |
          DDIFF=$(python -c "from datetime import date as d; print(abs((d.today() - d(2022, 9, 1)).days))")
          sed -i "s/DAY_COUNTER_VAR/$DDIFF/g" src/index.html

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=src
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}